GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "meetingTitle": "test name",
    "meetingTime": "21345",
    "isCommentMode": true,
    "commentMode": "10",
    "isReviewMode": true,
    "reviewMode": "33"
}